# Generated by Django 3.2.8 on 2021-10-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofexps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profexp',
            name='place',
            field=models.CharField(default='somewhere on Earth', max_length=100),
        ),
    ]
